### ISSUE TITLE
Bug: 16: bad-txns-in-belowout

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#24]
When requesting a DOI permission and utxos are available but not sufficient then transaction is created from our side successfully but Doichain node doesn't like it and responds with bad-txns-in-belowout. We must make sure that the chosen wallet has sufficient amount of funds before creating the transaction.

This is maybe an issue also when sending Doicoin in the wallet section. (please check)

**Comment by inspiraluna** [comment]
This needs to be reproduced - if still an issue!

**Comment by inspiraluna** [comment]
Need to create a test which sends more coins then existing!

**Comment by leKg1** [comment]
1) When trying to send a bigger amount it should show a error(amount is too big) below the input field of amount in red color by checking onChange event

2) Also the send button must be disable and enable

**Comment by leKg1** [comment]
Added error messages when sending coins in case incorrect amount or missing address and send button is disabled in each case.
 Please merge. branch: badTxnsInBelowout_24
