### ISSUE TITLE
please review and merge backButton_49 to master

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#61]
https://github.com/inspiraluna/doiContacts/commit/b3fb68f4f5f37215c46ceecafa711d1afc0a130b
seems like back-button implementation is not fully implemented and with a couple of half finished code.
some code parts of the cordova package seem to have no plugins installed. don't merge!

**Comment by leKg1** [comment]
this is fixed and implemented

**Comment by leKg1** [comment]
back_button_49

**Comment by inspiraluna** [comment]
merged to master
