### ISSUE TITLE
WalletCreator: When creating new seedphrase it needs to be validated better

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#62]
![Coinomi-Seedphrase-Check](https://user-images.githubusercontent.com/283618/75966829-c514f800-5eec-11ea-8131-4dcd14e2b160.png)

**Comment by leKg1** [comment]
this feature has been implemented. Please merge

**Comment by inspiraluna** [comment]
can you please also always tell me which branch I can should merge?

**Comment by leKg1** [comment]
seedPhraseValidation_62

**Comment by inspiraluna** [comment]
seems already merged.
