### ISSUE TITLE
When a wallet is busy calculating, display idle, loading or progress indication

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#63]
e.g. 
- when restoring a wallet from seed phrase (gathering many wallets)
- sending coins 
- adding contact
https://blog.stvmlbrn.com/2017/10/14/display-loading-indicator-in-react-during-ajax-requests.html

**Comment by leKg1** [comment]
implemented loading spinner when creating wallet and restoring wallets. Branch: loadingIndication_63

**Comment by inspiraluna** [comment]
merged current stage.  waiting for adding it to sending coins and contaccts
