### ISSUE TITLE
in case of wrong password (for recovery phrase / add wallet / send coins ...) display alert

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#66]
![IMAGE 2020-03-30 16:49:18](https://user-images.githubusercontent.com/283618/77926433-66059180-72a6-11ea-8525-623e29a54ff0.jpg)

**Comment by leKg1** [comment]
This has been implemented for recovery phrase / add wallet into the branch: passwordUnlockDialog_67
