### ISSUE TITLE
password unlock dialog when adding wallet / sending coins / etc.

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#67]
Please use forms-dialog: https://material-ui.com/components/dialogs/

Implement for 
- add wallet (including test)
- settings dialog to unlock seedphrase  (including test)
- sending coins  (including test)
- adding contact  (including test)
- decrypting seedphrase under settings  (including test)

**Comment by leKg1** [comment]
password unlock dialog has been implemented when adding wallet and into settings dialog to unlock seedPhrase. branch: passwordUnlockDialog_67
