### ISSUE TITLE
Receive Doicoin function should always generate new address

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#69]
Todo:
1. Generate the next address according to the derivation path 
2. it should be possible to copy the address to clipboard (as its done in WalletItem right now)
3. Remove "copy to clipboard function" from WalletItem

It is necessary to create an xpubKey in order to derive from it without decrypting a seedphrase for every single address: See: 

- https://github.com/bitcoinjs/bitcoinjs-lib/issues/997
- https://github.com/bitcoinjs/bitcoinjs-lib/issues/1238

**Comment by leKg1** [comment]
implemented generate new address into the branch: generateNewAddress_69
