### ISSUE TITLE
Change Theme of doiContact

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#72]
- change background / button Color of mainnet to violet (see doichain.org)
- change background / button Color of testnet to orange 
- enable dark mode

**Comment by leKg1** [comment]
Background/button color  changed on mainnet and testnet. Also  the dark mode has been enabled into the branch toggleTheme_72.
Please merge.

**Comment by inspiraluna** [comment]
Please check why the settings don't persist in cordova (android/ios emulator / phone)

**Comment by inspiraluna** [comment]
fixed in https://github.com/inspiraluna/doiContacts/commit/f5aefbe2acf9f6018d6647b1bac720d9bc031577
