### ISSUE TITLE
When sending Doicoin it should be possible to change between Schwartz (Satoshis) and DOI and other currencies

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#73]
In "Send coin" mode the amount textfield right now only accepts Schwartz (Doichain-Satoshis in our case).
We should have a little dropdown inside of the amounts textfield  where we can switch between 
DOI and Schwartz (and later Dollar, Euro and Bitcoin) 

https://material-ui.com/components/text-fields/

When entering the value e.g. 1 DOI it should be possible to switch to Schwartz and the amount inside the component should be 100 000 000 Schwartz. 

Please use S for Schwartz 
and DOI for Doicoin.

1. Implement the component with the to Symbols (S and DOI)

**Comment by leKg1** [comment]
This feature has been implemented into the branch toggleCurrency_73, please merge.

**Comment by inspiraluna** [comment]
https://github.com/inspiraluna/doiContacts/commit/e1e73a3e9329a975013c615437f12a4dd3c25d87
