### ISSUE TITLE
DOI/Schwartz should be possible to change in Settings

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#76]
- add switch or dropdown with "DOI/Schwartz" in settings 
- add a switch possibility in WalletList - when touching/clicking on balance switch between DOI/Schwartz
- add a switch possibility in WalletItem - when touching/clicking on balance switch between DOI/Schwartz

**Comment by inspiraluna** [comment]
https://github.com/inspiraluna/doiContacts/commit/e1e73a3e9329a975013c615437f12a4dd3c25d87

**Comment by leKg1** [comment]
this feature has been implemented.
https://github.com/inspiraluna/doiContacts/commit/ac430ffaf87e6e92445db0b367ca4d192c6dc3be 
branch: toggleCurrency_76
Please merge.
