### ISSUE TITLE
E2ETests Improvements

### ISSUE THREAD

**Issue by inspiraluna** [inspiraluna/doiContacts#95]
- put wallet tests into new test suite inside wallets.e2e.test (done)
- put contact tests into new test suite inside contact.e2e.test (done)
- put settings tests into new test suite inside settings.e2e.test (done)

- refactoring of each of the tests necessary put repeating code into functions!  (see TODO comment in test code)

**Comment by leKg1** [comment]
1) TODO please create a function for updating a wallet including checking the details via asserts - 2h
2) TODO add contact should be a function not implemented twice! - 2h
3) TODO Please create a walletcreator.e2e.js file and put it there AND also test this in settings! -2h
4) TODO please add test to check if status shows current network - 1h
5) TODO please check if button, label texts are their value too! - 1h

**Comment by inspiraluna** [comment]
Please see comments in the commit. Function for addContact is missing paramters. Please improve.

**Comment by leKg1** [comment]
The function addContact has been improved with the parameter "email"
